# It contains all the configs required in the project
data:

  source_url: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip"
  local_dir: data
  data_file: data.zip
  unzip_data_dir: data
  bad_data_dir: bad_data
  parent_data_dir: PetImages


params:
  img_shape: [180,180,3]
  lr: 0.001
  loss: spare_categorical_crossentropy
  metrics: ["accuracy"]




